# Generated by Django 3.1.2 on 2020-11-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussd',
            name='newreq',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ussd',
            name='session_id',
            field=models.IntegerField(unique=True),
        ),
    ]
