# Generated by Django 3.1.2 on 2020-11-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapp', '0003_auto_20201106_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ussd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=13)),
                ('session_id', models.IntegerField(unique=True)),
                ('input', models.CharField(max_length=40)),
                ('newreq', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bankUser',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='From',
        ),
        migrations.DeleteModel(
            name='SessionLevel',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='BankTransaction',
        ),
        migrations.DeleteModel(
            name='BankUser',
        ),
    ]
