# Generated by Django 3.1.2 on 2020-11-06 20:45

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapp', '0004_auto_20201106_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msisdn', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=30, unique=True)),
                ('lang', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
